services:
  mysql:
    container_name: mysql
    image: mysql:8.4.3-oraclelinux9
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8080:8080"
    environment:
      APACHE_PORT: 8080
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: always
  mongo:
    container_name: mongo
    image: mongo:8.0.3-noble
    ports:
      - "27017:27017"
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

volumes:
  mysql:
  mongo_configdb:
  mongo_db:
